<Project>
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<OutputType>Library</OutputType>
		
		<DefineConstants>noMY_TRACE;noDISABLE_DEBUGGER_HIDDEN</DefineConstants>
		<InvariantGlobalization>true</InvariantGlobalization>
		<Nullable>enable</Nullable>
		<Deterministic>true</Deterministic>
		<AnalysisLevel>preview-all</AnalysisLevel>
		<NoWarn>659,661,8604,8618</NoWarn>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<EnableSourceControlManagerQueries>false</EnableSourceControlManagerQueries>
		<ExperimentalFileBasedProgramEnableIncludeDirective>true</ExperimentalFileBasedProgramEnableIncludeDirective>
		<ExperimentalFileBasedProgramEnableTransitiveDirectives>true</ExperimentalFileBasedProgramEnableTransitiveDirectives>
	</PropertyGroup>
</Project>