name: .NET CI + Coverage + SonarCloud

on:
  push:
    branches: [ Main ]
  
  workflow_dispatch:

env:
  BUILD_VERSION: 0.0.0-PreAlpha.${{ github.run_number }}

jobs:
  run:
    runs-on: windows-latest
    
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.100-rc.1.25451.107
      -
        name: Install global tools
        shell: pwsh
        run: |
          dotnet tool install --global "dotnet-coverage"
          dotnet tool install --global "dotnet-sonarscanner"
          $env:PATH += ";${env:USERPROFILE}\.dotnet\tools"
      -
        name: NuGet restore
        run: dotnet restore SPO_CS/SPO_CS.csproj
      -
        name: sonarscanner begin
        continue-on-error: true
        run: >
          dotnet sonarscanner begin
          /o:"sk-genius"
          /k:"SK-Genius_SPO-PreAlpha"
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      -
        name: Build
        run: >
          dotnet build SPO_CS/SPO_CS.csproj
          --no-incremental
          --configuration Debug
      -
        name: dotnet-coverage xml for SonarCloud
        continue-on-error: true
        run: >
          dotnet-coverage collect
          "SPO_CS\bin\Debug\net10.0\SPO_CS.exe"
          -f xml
          -o coverage.xml
      -
        name: sonarscanner end
        continue-on-error: true
        run: >
          dotnet sonarscanner end
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      -
        name: dotnet-coverage dotnet-coverage for Codecov
        continue-on-error: true
        run: >
          dotnet-coverage collect
          "SPO_CS\bin\Debug\net10.0\SPO_CS.exe"
          -f c
      -
        name: Upload coverage to Codecov
        continue-on-error: true
        uses: codecov/codecov-action@v4
        with:
          files: output.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ env.BUILD_VERSION }}
        env:
          CI: true
